# src/main/resources/application-staging.yml
spring:
  application:
    name: employee-payroll-system-staging

  # Staging Database - Postgres (instead of H2)
  datasource:
    url: jdbc:postgresql://payroll-prod-db.chxxo89q9lcl.us-east-1.rds.amazonaws.com:5432/payroll_staging
    driver-class-name: org.postgresql.Driver
    username: payroll_user
    password: SecurePassword123!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  # JPA Settings for Postgres in Staging
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update     # or validate, depending on your staging strategy
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Staging Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:rawang17@gmail.com}
    password: ${SMTP_PASSWORD:fswc bscf gnyb iewm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# API Documentation for Staging Tests
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs-ui
  api-docs:
    path: /v3/api-docs

# Staging JWT Configuration
auth:
  jwt:
    secret-key: ${JWT_SECRET:staging-jwt-secret-key-for-testing-67890}
    token-expiration: 3600000  # 1 hour

# Staging Logging
logging:
  level:
    com.example.payroll: INFO
    org.springframework.security: WARN

# Only expose health/info/metrics in staging
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
