spring:
  application:
    name: employee-payroll-system-staging
  
  # Staging Database - H2 for Testing
  datasource:
    url: jdbc:h2:mem:stagingdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: staging_user
    password: staging_pass
  
  # Staging JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Staging Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:rawang17@gmail.com}
    password: ${SMTP_PASSWORD:fswc bscf gnyb iewm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# API Documentation for Staging Tests
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs-ui
  api-docs:
    path: /v3/api-docs

# Staging JWT Configuration
auth:
  jwt:
    secret-key: ${JWT_SECRET:staging-jwt-secret-key-for-testing-67890}
    token-expiration: 3600000  # 1 hour

# Staging Logging
logging:
  level:
    com.example.payroll: INFO
    org.springframework.security: WARN

# Selected Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
