# src/main/resources/application-dev.yml
spring:
  application:
    name: employee-payroll-system-dev

  # Development Database - Postgres (instead of H2)
  datasource:
    url: jdbc:postgresql://payroll-prod-db.chxxo89q9lcl.us-east-1.rds.amazonaws.com:5432/payroll_prod
    driver-class-name: org.postgresql.Driver
    username: payroll_user
    password: SecurePassword123!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  # Development JPA Settings for Postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update     # Allow schema changes in dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # (Remove H2 console, since H2 is gone)
  h2:
    console:
      enabled: false

  # Development Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: rawang17@gmail.com
    password: fswc bscf gnyb iewm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# API Documentation for Development
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs-ui
  api-docs:
    path: /v3/api-docs

# Development JWT Settings
auth:
  jwt:
    secret-key: development-jwt-secret-key-for-testing-12345
    token-expiration: 36000000  # 10 hours (for convenience)

# Development Logging - Verbose
logging:
  level:
    com.example.payroll: DEBUG
    org.springframework.security: DEBUG

# Enable all Actuator endpoints in Development
management:
  endpoints:
    web:
      exposure:
        include: "*"   # show all endpoints in dev
