# src/main/resources/application-dev.yml
spring:
  application:
    name: employee-payroll-system-dev

  # ────────────────────────────────────────────────────────────────
  # 1) DEVELOPMENT DATASOURCE → H2 (IN‐MEMORY)
  # ────────────────────────────────────────────────────────────────
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

    # (Optional) Adjust Hikari settings if you want:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  # ────────────────────────────────────────────────────────────────
  # 2) JPA / HIBERNATE FOR H2
  # ────────────────────────────────────────────────────────────────
  jpa:
    # Hibernate will auto‐discover H2 dialect, but being explicit is okay
    database-platform: org.hibernate.dialect.H2Dialect

    # Create tables on startup, drop them on shutdown:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ────────────────────────────────────────────────────────────────
  # 3) H2 CONSOLE (DEV‐ONLY)
  # ────────────────────────────────────────────────────────────────
  h2:
    console:
      enabled: true
      path: /database-console

  # ────────────────────────────────────────────────────────────────
  # 4) DEV MAIL (can reuse your Gmail credentials for local testing)
  # ────────────────────────────────────────────────────────────────
  mail:
    host: smtp.gmail.com
    port: 587
    username: rawang17@gmail.com
    password: fswc bscf gnyb iewm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ────────────────────────────────────────────────────────────────
# 5) SWAGGER / OPENAPI FOR DEV
# ────────────────────────────────────────────────────────────────
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs-ui
  api-docs:
    path: /v3/api-docs

# ────────────────────────────────────────────────────────────────
# 6) JWT (DEV SECRET + LONG EXPIRATION)
# ────────────────────────────────────────────────────────────────
auth:
  jwt:
    secret-key: development-jwt-secret-key-for-testing-12345
    token-expiration: 36000000   # 10 hours

# ────────────────────────────────────────────────────────────────
# 7) DEV LOGGING (VERBOSE)
# ────────────────────────────────────────────────────────────────
logging:
  level:
    com.example.payroll: DEBUG
    org.springframework.security: DEBUG

# ────────────────────────────────────────────────────────────────
# 8) DEV ACTUATOR (Expose Everything)
# ────────────────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: "*"
