spring:
  profiles: prod

  # == PRODUCTION (RDS/Postgres) ==
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME:employee_payroll_db}
    username: ${DATABASE_USER:admin_user}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      connection-timeout: 20000
      idle-timeout: 600000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20

  mail:
    username: ${SMTP_USER}
    password: ${SMTP_PASS}

logging:
  level:
    com.example.payroll: INFO
    org.springframework.security: WARN
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

server:
  port: ${APP_PORT:8080}
  compression:
    enabled: true
