spring:
  application:
    name: employee-payroll-system-dev

  # H2 Database (In-Memory)
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  # JPA/Hibernate for H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console
  h2:
    console:
      enabled: true
      path: /database-console

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: rawang17@gmail.com
    password: fswc bscf gnyb iewm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT (Dev)
auth:
  jwt:
    secret-key: development-jwt-secret-key-for-testing-12345
    token-expiration: 36000000   # 10 hours

# Logging (Verbose)
logging:
  level:
    com.example.payroll: DEBUG
    org.springframework.security: DEBUG

# Actuator (All endpoints)
management:
  endpoints:
    web:
      exposure:
        include: "*"

