# src/main/resources/application-staging.yml
spring:
  application:
    name: employee-payroll-system-staging

  # ────────────────────────────────────────────────────────────────
  # 1) STAGING DATASOURCE → POSTGRES ON RDS
  # ────────────────────────────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://payroll-prod-db.chxxo89q9lcl.us-east-1.rds.amazonaws.com:5432/payroll_staging
    driver-class-name: org.postgresql.Driver
    username: payroll_user
    password: SecurePassword123!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  # ────────────────────────────────────────────────────────────────
  # 2) JPA / HIBERNATE FOR POSTGRES (STAGING)
  # ────────────────────────────────────────────────────────────────
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update    # will apply any schema changes automatically
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # ────────────────────────────────────────────────────────────────
  # 3) MAIL FOR STAGING
  # ────────────────────────────────────────────────────────────────
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:rawang17@gmail.com}
    password: ${SMTP_PASSWORD:fswc bscf gnyb iewm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ────────────────────────────────────────────────────────────────
# 4) SWAGGER / OPENAPI FOR STAGING
# ────────────────────────────────────────────────────────────────
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs-ui
  api-docs:
    path: /v3/api-docs

# ────────────────────────────────────────────────────────────────
# 5) JWT (STAGING SECRET)
# ────────────────────────────────────────────────────────────────
auth:
  jwt:
    secret-key: ${JWT_SECRET:staging-jwt-secret-key-for-testing-67890}
    token-expiration: 3600000   # 1 hour

# ────────────────────────────────────────────────────────────────
# 6) LOGGING FOR STAGING
# ────────────────────────────────────────────────────────────────
logging:
  level:
    com.example.payroll: INFO
    org.springframework.security: WARN

# ────────────────────────────────────────────────────────────────
# 7) ACTUATOR – only show health/info/metrics in staging
# ────────────────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
