# src/main/resources/application-prod.yml
#
# ─────────────────────────────────────────────────────────────────────────────
# Production configuration for Employee Payroll System (profile = "prod")
# ─────────────────────────────────────────────────────────────────────────────

spring:
  application:
    name: payroll-prod

  # ────────────────────────────── PostgreSQL Database ─────────────────────────────
  datasource:
    url: jdbc:postgresql://kareem-db.chxxo89q9lcl.us-east-1.rds.amazonaws.com:5432/payroll_prod
    driver-class-name: org.postgresql.Driver
    username: payroll_user
    password: SecurePassword123!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000

  # ─────────────────── JPA/Hibernate for PostgreSQL ───────────────────
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # Never modify schema in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25

  # ────────────────────────────── Mail (env variables) ─────────────────────────────
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ────────────────────────────────── Swagger (Prod) ─────────────────────────────────
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

# ──────────────────────────────── JWT (Prod) ────────────────────────────────
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1800000   # 30 minutes

# ───────────────────────────── Logging (Minimal) ─────────────────────────────
logging:
  level:
    com.example.payroll: WARN
    org.springframework.security: ERROR
    root: ERROR

# ─────────────────────────────────── Actuator (Prod) ───────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers  # only expose a small subset in production
  endpoint:
    health:
      show-details: never                    # never show sensitive details
      probes:
        enabled: false                       # disable liveness/readiness probes if any
      db:
        enabled: false                       # turn off database health check (so Health = UP always)
      mail:
        enabled: false                       # turn off mail health check entirely

# ─────────────────────────────────── Server Settings ───────────────────────────────────
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  error:
    include-stacktrace: never
