spring:
  application:
    name: payroll-prod

  # PostgreSQL Database
  datasource:
    url: jdbc:postgresql://kareem-db.chxxo89q9lcl.us-east-1.rds.amazonaws.com:5432/payroll_prod
    driver-class-name: org.postgresql.Driver
    username: payroll_user
    password: SecurePassword123!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000

  # JPA/Hibernate for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # Never modify schema in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25

  # Mail (Environment variables)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

# JWT (Production)
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1800000   # 30 minutes

# Logging (Minimal)
logging:
  level:
    com.example.payroll: WARN
    org.springframework.security: ERROR
    root: ERROR

# Actuator (Minimal)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# Server
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  error:
    include-stacktrace: never