# src/main/resources/application-prod.yml
spring:
  application:
    name: employee-payroll-system-prod

  # ── Production Database Configuration ───────────────────────────────────────
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME:payroll_prod}?sslmode=require
    username: ${DATABASE_USER:payroll_user}
    password: SecurePassword123!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      connection-timeout: 20000
      idle-timeout: 600000

  # ── Hibernate & JPA Settings ────────────────────────────────────────────────
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update       # Changed from validate → update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20

  # ── SMTP Email Service Configuration ───────────────────────────────────────
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ── OpenAPI / Swagger ────────────────────────────────────────────────────────
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs-ui
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs

# ── Authentication & Security ─────────────────────────────────────────────────
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    token-expiration: 1800000

# ── Logging ──────────────────────────────────────────────────────────────────
logging:
  level:
    com.example.payroll: INFO
    org.springframework.security: WARN
    root: WARN

# ── Health & Monitoring ──────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# ── Server Configuration ────────────────────────────────────────────────────
server:
  port: ${APP_PORT:8080}
  compression:
    enabled: true
  error:
    include-stacktrace: never
  forward-headers-strategy: framework
